config/routes.rb
SurveyGorilla::Application.routes.draw do
  
  root to: 'surveys#index'
  resources :surveys

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  attr_accessible :body
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
  accepts_nested_attributes_for :questions, allow_destroy: true
  attr_accessible :title, :questions_attributes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def new
    @survey = Survey.new
    3.times do 
      @survey.questions << Question.new
    end
  end

  def create
    p '*' * 100
    p params
    p '*' * 100
    @survey = Survey.create( params[:survey] )
    redirect_to survey_path(@survey)
  end

  def index
  end

  def show
    p '*' * 80
    p params
    p '*' * 80
    @survey = Survey.find(params[:id])
  end

  def update
    p '%' * 100
    p params
    @survey = Survey.find(params[:id])
    @survey.update_attributes(:title => params[:string])
    render :json => @survey
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyGorilla</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/surveys/index.html.erb
index.html.erb <br>

<%= link_to "+ Create Survey", new_survey_path %>

app/views/surveys/new.html.erb
<h3>Create a new survey!</h3>

<%= form_for @survey do |survey_form| %>
  Survey title: <%= survey_form.text_field :title %><br />

  <%= survey_form.fields_for :questions, @survey.questions do |question_fields| %>
  Question body: <%= question_fields.text_field :body %><br />
  <% end %>

  <%= survey_form.submit %>
<% end %>

app/views/surveys/show.html.erb
<h1> This is your beautiful survey. </h1>

<div id="edit_survey_and_questions">
  <div id="edit_survey" contenteditable="true">
    <%= @survey.title %><br />
  </div>
    <% @survey.questions.each do |question| %>
  <div id="edit_question" contenteditable="true">
      <%= question.body %><br />
  </div>
    <% end %>
  <div id="update_button"><%= button_to "Update Survey Title", survey_path(@survey) %>
  </div>
</div>